-- 创建额外的数据库
CREATE DATABASE IF NOT EXISTS copiioai_db;

-- 创建知识表
USE copiioai_db;
CREATE TABLE  knowledge (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    question VARCHAR(128) NOT NULL,
	description VARCHAR(4096) NOT NULL Default '',
	answer VARCHAR(4096) NOT NULL,
	public tinyint UNSIGNED NOT NULL DEFAULT 1,
    status tinyint UNSIGNED NOT NULL DEFAULT 1,
	embedding_id BIGINT(64) UNSIGNED NOT NULL,
	model_name VARCHAR(200) NOT NULL DEFAULT '',
	tool_id BIGINT(64) UNSIGNED NOT NULL,
	params VARCHAR(4096) NOT NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user_id_status (user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建工具表
CREATE TABLE  tools (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(128) NOT NULL,
	description VARCHAR(4096) NOT NULL DEFAULT '',
	url VARCHAR(1024) NOT NULL,
	push TINYINT UNSIGNED NOT NULL DEFAULT 1,
	public tinyint UNSIGNED NOT NULL DEFAULT 1,
    status tinyint UNSIGNED NOT NULL DEFAULT 1,
	timeout SMALLINT UNSIGNED NOT NULL,
	params VARCHAR(4096) NOT NULL DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    KEY idx_user_id_status (user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建用户表
CREATE TABLE users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED UNIQUE NOT NULL,
    firebase_uid BIGINT UNSIGNED UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255),
    oauth_provider VARCHAR(255),
    oauth_provider_id VARCHAR(255),
    is_active TINYINT UNSIGNED DEFAULT TRUE,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建知识授权表
CREATE TABLE knowledge_share (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    from_user_id BIGINT UNSIGNED NOT NULL,
    from_user_email VARCHAR(255) NOT NULL DEFAULT '',
    to_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    to_user_email VARCHAR(255) NOT NULL DEFAULT '',
    knowledge_id BIGINT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED DEFAULT TRUE,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	KEY idx_to_user_email (to_user_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 场景定义表
CREATE TABLE IF NOT EXISTS scenes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(256) DEFAULT '',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 用户场景订阅表
CREATE TABLE IF NOT EXISTS user_scenes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    scene_id BIGINT UNSIGNED NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_scene (user_id, scene_id),
    KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- knowledge 表增加场景标签字段
ALTER TABLE knowledge ADD COLUMN IF NOT EXISTS scene_id BIGINT UNSIGNED DEFAULT NULL;
ALTER TABLE knowledge ADD INDEX IF NOT EXISTS idx_scene_id (scene_id);

-- 初始场景：专利检索
INSERT INTO scenes (name, description) VALUES ('专利检索', '专利检索相关能力，包含专利查询、分析、申请等');

-- 存量用户默认订阅专利检索场景（部署时执行）
-- INSERT IGNORE INTO user_scenes (user_id, scene_id) SELECT user_id, 1 FROM users;